version: '3.8'

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile.app
        container_name: laravel_app
        restart: unless-stopped
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel_db
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=your_password
        volumes:
            - ../:/var/www
        networks:
            - app-network

    web:
        build:
            context: ..
            dockerfile: docker/Dockerfile.nginx
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: your_password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    worker:
        build:
            context: ..
            dockerfile: docker/Dockerfile.app
        container_name: laravel_worker
        restart: unless-stopped
        command: php artisan queue:work
        volumes:
            - ../:/var/www
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
