name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file
        run: |
          cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --seed

      - name: Run tests
        run: php artisan test

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_TEST_LARAVEL_11 }}

      - name: Prepare server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.64.204.123 << 'EOF'
          sudo mkdir -p /var/www/laravel
          sudo chown -R ubuntu:ubuntu /var/www/laravel
          sudo chmod -R u+w /var/www/laravel
          EOF

      - name: Sync files to server
        run: |
          rsync -avz --delete  --no-times --no-perms \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ubuntu@52.64.204.123:/var/www/laravel --rsync-path="sudo rsync"

      - name: Run deployment commands on server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.64.204.123 << 'EOF'
          sudo mkdir -p /var/www/laravel/storage/logs
          sudo chmod -R 777 /var/www/laravel/storage/logs
          sudo chmod -R 777 /var/www/laravel/storage
          sudo touch /var/www/laravel/storage/logs/laravel.log
          sudo chmod -R 777 /var/www/laravel/storage/logs/laravel.log
          cd /var/www/laravel
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          EOF

